USE [master]
GO
CREATE DATABASE [userDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'userDb', FILENAME = N'/var/opt/mssql/data/userDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'userDb_log', FILENAME = N'/var/opt/mssql/data/userDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [userDb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [userDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [userDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [userDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [userDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [userDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [userDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [userDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [userDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [userDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [userDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [userDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [userDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [userDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [userDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [userDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [userDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [userDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [userDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [userDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [userDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [userDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [userDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [userDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [userDb] SET RECOVERY FULL 
GO
ALTER DATABASE [userDb] SET  MULTI_USER 
GO
ALTER DATABASE [userDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [userDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [userDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [userDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [userDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [userDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'userDb', N'ON'
GO
ALTER DATABASE [userDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [userDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [userDb]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 10/02/2024 15:26:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](max) NOT NULL,
	[BirthDate] [datetime2](7) NOT NULL,
	[IncomeValue] [decimal](18, 2) NOT NULL,
	[Cpf] [nvarchar](max) NOT NULL,
	[CreateDate] [datetime2](7) NOT NULL,
	[UpdateDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [userDb] SET  READ_WRITE 
GO
